CREATE DATABASE HC;

USE HC;

CREATE TABLE Healthcare (
    Name VARCHAR(100),
    Age INT,
    Gender VARCHAR(10),
    BloodType VARCHAR(5),
    HEALTH_Condition VARCHAR(50),
    AdmissionDate DATE,
    Doctor VARCHAR(100),
    Hospital VARCHAR(100),
    Insurance VARCHAR(50),
    BillingAmount DECIMAL(15,2),
    RoomNumber INT,
    AdmissionType VARCHAR(20),
    DischargeDate DATE,
    Medication VARCHAR(50),
    TestResults VARCHAR(20)
);


SELECT * FROM HEALTHCARE;
SELECT * FROM HEALTHCARE WHERE INSURANCE LIKE "%Bl%";
SELECT * FROM HEALTHCARE WHERE GENDER="Male";
SELECT * FROM HEALTHCARE WHERE DOCTOR="JUSTIN KIM";

SELECT COUNT(*) FROM HEALTHCARE WHERE BLOODTYPE="A+" AND HEALTH_CONDITION="CANCER";

SELECT MIN(AGE) AS MIN_AGE, MAX(AGE) AS MAX_AGE FROM HEALTHCARE;

SELECT NAME, AGE, HEALTH_CONDITION FROM HEALTHCARE WHERE HEALTH_CONDITION="CANCER" OR HEALTH_CONDITION="DIABEES";








-- -----------------------------------------

-- START HERE
SELECT * FROM HEALTHCARE WHERE AGE IN (30,31,32,33,34,35);
SELECT * FROM HEALTHCARE WHERE AGE BETWEEN 18 AND 20;

SELECT * FROM HEALTHCARE ORDER BY BillingAmount DESC;


SELECT * FROM HEALTHCARE WHERE NOT HEALTH_CONDITION="CANCER";

SELECT DISTINCT HEALTH_CONDITION FROM HEALTHCARE;

SELECT * FROM HEALTHCARE WHERE AGE IS NULL;


SELECT * FROM HEALTHCARE;

SET SQL_SAFE_UPDATES = 0;

UPDATE HEALTHCARE SET AGE =null WHERE NAME = 'Bobby JacksOn';

CREATE DATABASE STUDENT;
USE STUDENT;
CREATE TABLE MARKSHEET(
STUDENT_ID INT,
NAME VARCHAR(100),
TOTAL_MARKS INT);

